// =============================================================================
// realDeal/run.js — thin orchestrator: build the localnet adapter, run the
// SAME shared scenario as demoLand, with real ZK proofs this time.
//
// Prerequisites:
//   npm run compile-contract-zk   (full compile with prover/verifier keys)
//   npm run infra:up              (node + indexer + proof server)
// Run:
//   npm run realdeal
// =============================================================================

import { runScenario } from '../shared/scenario.js';
import { makeNarrator } from '../shared/narrator.js';
import { makeLocalnetAdapter } from './adapter.js';

const say = makeNarrator({ mode: 'realDeal (live Midnight localnet, real ZK proofs)' });

let adapter;
try {
  adapter = await makeLocalnetAdapter(say);
  await runScenario(adapter, say);
  console.log('  realDeal run complete — every ✔ above was a REAL zero-knowledge');
  console.log('  proof generated by the proof server and landed on the localnet.\n');
} catch (err) {
  console.error('\n  DEMO ABORTED:', err.message ?? err);
  process.exitCode = 1;
} finally {
  await adapter?.shutdown?.();
  // Wallet subscriptions keep the event loop alive; exit explicitly.
  setTimeout(() => process.exit(process.exitCode ?? 0), 1500);
}
